#### Numpy

- Numpy(Numerical Python) is a pyton library for fast numerical computations
- Provides multidimensional arrays(faster than python lists)
- Used heavily in data science, machine learning, image processing and deep learning

#### Why Numpy instead of Lists?

- Python lists are slow and take more memory

- Numpy arrays are:
    - lkfjds

In [1]:
import numpy as np

In [2]:
# From List

arr = np.array([2, 3, 4, 5, 8])
print(arr)
print(type(arr))

[2 3 4 5 8]
<class 'numpy.ndarray'>


In [4]:
# Array Dimensions

# 1D Array
a = np.array([1, 2, 3])

# 2D Array
b = np.array([[1, 2, 3], [4, 5, 6]])

# 3D Array
c = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

# View Dimension
print(a.ndim)
print(b.ndim)
print(c.ndim)

print(a)
print(b)
print(c)

1
2
3
[1 2 3]
[[1 2 3]
 [4 5 6]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [ ]:
# Useful Array Creation Methods

np.zeros((2, 3))     # 2x3 with 0's

array([[0., 0., 0.],
       [0., 0., 0.]])

In [6]:
np.ones((3, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [12]:
np.full((4, 6), 3)  # 2x2 filled with 7

array([[3, 3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3, 3]])

In [13]:
np.eye(3) # Identity matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [16]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [28]:
print(np.linspace(0, 10, 6)) # Divide in parts provided in parameter
print(np.linspace(0, 10, 5))
# np.linspace(a, b, c) # divide the a to b in c parts whoose difference is same
print(np.linspace(10, 20, 6))

[ 0.  2.  4.  6.  8. 10.]
[ 0.   2.5  5.   7.5 10. ]
[10. 12. 14. 16. 18. 20.]


In [29]:
# Array Indexing and Slicing

arr = np.array([10, 20, 30, 40, 50])

print(arr[0])
print(arr[-1])
print(arr[1: 4])

10
50
[20 30 40]


In [ ]:
# 2D Example

mat = np.array([[1, 2, 3], [4, 5, 6]])

print(mat)
print(mat[0, 1])
print(mat[:, 1]) # [2, 5] all rows 1st column
print("*******")
print(mat[1, :])    # [4, 5, 6] all columns 1 rows

[[1 2 3]
 [4 5 6]]
2
[2 5]
*******
[4 5 6]


In [36]:
# Array Operations

x = np.array([1, 2, 3])
y = np.array([4, 5, 6])

print(x+y)
print(x-y)
print(x*y)
print(x/y)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]


In [41]:
# Mathematical Functions

arr = np.array([0, 1, 2, 3, 4, 5, 6])

print(np.mean(arr))
print(np.median(arr))
print(np.std(arr))
print(np.sum(arr))
print(np.max(arr))
print(np.min(arr))

3.0
3.0
2.0
21
6
0


In [44]:
# Reshaping Arrays

arr = np.arange(12)
print(arr)

reshaped = arr.reshape(3, 4)
print(reshaped)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
