#### Numpy

- Numpy(Numerical Python) is a pyton library for fast numerical computations
- Provides multidimensional arrays(faster than python lists)
- Used heavily in data science, machine learning, image processing and deep learning

#### Why Numpy instead of Lists?

- Python lists are slow and take more memory

- Numpy arrays are:
    - lkfjds

In [1]:
import numpy as np

In [2]:
# From List

arr = np.array([2, 3, 4, 5, 8])
print(arr)
print(type(arr))

[2 3 4 5 8]
<class 'numpy.ndarray'>


In [4]:
# Array Dimensions

# 1D Array
a = np.array([1, 2, 3])

# 2D Array
b = np.array([[1, 2, 3], [4, 5, 6]])

# 3D Array
c = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

# View Dimension
print(a.ndim)
print(b.ndim)
print(c.ndim)

print(a)
print(b)
print(c)

1
2
3
[1 2 3]
[[1 2 3]
 [4 5 6]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
